[Service]
Environment=GOROOT=/usr/lib/go-1.26
Environment=GOPATH=/root/go
Environment=PATH=/usr/lib/go-1.26/bin:/root/go/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
